const imageMap: { [key: string]: any } = {
    'deck.png': require('./assets/images/deck.png'),
    'deckoutside.jpeg': require('./assets/images/deckoutside.jpeg'),
    'finefood.jpeg': require('./assets/images/finefood.jpeg'),
    'finefoodinside.png': require('./assets/images/finefoodinside.png'),
    'flavours.jpeg': require('./assets/images/flavours.jpeg'),
    'flavoursinside.jpeg': require('./assets/images/flavoursinside.jpeg'),
    'frontier.png': require('./assets/images/frontier.png'),
    'frontierinside.jpeg': require('./assets/images/frontierinside.jpeg'),
    'mbinside.jpeg': require('./assets/images/mbinside.jpeg'),
    'mbinside2.jpeg': require('./assets/images/mbinside2.jpeg'),
    'pgp.jpeg': require('./assets/images/pgp.jpeg'),
    'pgpfood.jpeg': require('./assets/images/pgpfood.jpeg'),
    'reedz.jpeg': require('./assets/images/reedz.jpeg'),
    'reedzfood.jpeg': require('./assets/images/reedzfood.jpeg'),
    'spread.jpeg': require('./assets/images/spread.jpeg'),
    'spreadoutside.jpeg': require('./assets/images/spreadoutside.jpeg'),
    'teaparty.jpeg': require('./assets/images/teaparty.jpeg'),
    'teapartyinside.jpeg': require('./assets/images/teapartyinside.jpeg'),
    'techno.jpeg': require('./assets/images/techno.jpeg'),
    'technoinside.jpeg': require('./assets/images/technoinside.jpeg'),
    'terrace.png': require('./assets/images/terrace.png'),
    'terraceoutside.jpeg': require('./assets/images/terraceoutside.jpeg'),
    'tomoro.jpeg': require('./assets/images/tomoro.jpeg'),
    'tomoro-drinks.jpeg': require('./assets/images/tomoro-drinks.jpeg'),
  };
  
  export default imageMap;